#!/bin/bash
################################################################################
# Script: comparative_analysis.sh
# Purpose: Generate pretty-printed comparison analysis from JSON provider data
# Usage: ./comparative_analysis.sh <input.json> [output_report.txt]
#
# Features:
#   - Full provider/SKU summary
#   - Specialized analysis for Microsoft.Compute (family/version breakdowns)
#   - Specialized analysis for Microsoft.Storage (account kind breakdowns)
#   - Comparative metrics showing differences between regions
################################################################################

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
JSON_FILE="${1:-}"
OUTPUT_FILE="${2:-}"

# Display help message
show_help() {
    cat << 'EOF'
Usage: ./comparative_analysis.sh <input.json> [output_report.txt] [OPTIONS]

Required Arguments:
  <input.json>                Path to JSON provider comparison file
                              (generated by services_compare.sh)

Optional Arguments:
  [output_report.txt]         Output file for analysis report (default: stdout)
  --help, -h                  Display this help message

Description:
  Generates a comprehensive Azure service comparison report from provider JSON data.
  
  The report includes:
    • Summary statistics (provider availability, status breakdown)
    • Microsoft.Compute analysis (family/version SKU distribution)
    • Microsoft.Storage analysis (account type distribution)
    • Top 15 providers with notable differences
    • Regional capability comparison

Examples:
  # Display report to stdout
  ./comparative_analysis.sh output/westus2_vs_swedencentral_providers.json

  # Save report to file
  ./comparative_analysis.sh output/westus2_vs_swedencentral_providers.json report.txt

  # Display help
  ./comparative_analysis.sh --help

Notes:
  - Input JSON must be generated by services_compare.sh
  - Region names are extracted from JSON metadata
  - Output uses UTF-8 box drawing characters

EOF
}

# Parse arguments
for arg in "$@"; do
    case "$arg" in
        --help|-h)
            show_help
            exit 0
            ;;
    esac
done

if [[ -z "$JSON_FILE" ]]; then
    echo "Error: Missing required argument <input.json>"
    echo ""
    show_help
    exit 1
fi

if [[ ! -f "$JSON_FILE" ]]; then
    echo "Error: JSON file not found: $JSON_FILE"
    exit 1
fi

# Detect input schema (provider comparison vs inv.sh availability comparison)
INPUT_SCHEMA=$(jq -r '
    if type == "array" and length > 0 and (.[0] | type == "object") then
        if (.[0] | has("provider") and has("sourceRegion") and has("targetRegion")) then
            "provider"
        elif (.[0] | has("serviceType") and has("availability")) then
            "service_availability"
        else
            "unknown"
        end
    else
        "unknown"
    end
' "$JSON_FILE" 2>/dev/null || echo "unknown")

# Extract region names from JSON
if [[ "$INPUT_SCHEMA" == "provider" ]]; then
    SOURCE_REGION=$(jq -r '.[0].sourceRegion.name' "$JSON_FILE" 2>/dev/null || echo "Unknown")
    TARGET_REGION=$(jq -r '.[0].targetRegion.name' "$JSON_FILE" 2>/dev/null || echo "Unknown")
elif [[ "$INPUT_SCHEMA" == "service_availability" ]]; then
    # Determine regions from the availability matrix
    regions=$(jq -r '[.[].availability[].region] | unique | .[]' "$JSON_FILE" 2>/dev/null || true)
    SOURCE_REGION=$(echo "$regions" | sed -n '1p')
    TARGET_REGION=$(echo "$regions" | sed -n '2p')
    SOURCE_REGION=${SOURCE_REGION:-Unknown}
    TARGET_REGION=${TARGET_REGION:-Unknown}
else
    SOURCE_REGION="Unknown"
    TARGET_REGION="Unknown"
fi

# Detect input type from filename (inventory vs full service comparison)
INPUT_TYPE="service"
if [[ "$JSON_FILE" == *"inventory_"* ]]; then
    INPUT_TYPE="inventory"
fi

# Adjust output file naming if not specified
if [[ -z "$OUTPUT_FILE" ]] && [[ -n "${2:-}" ]] && [[ "${2:-}" != "--"* ]]; then
    OUTPUT_FILE="${2:-}"
elif [[ -z "$OUTPUT_FILE" ]] && [[ -t 1 ]]; then
    # stdout, no adjustment needed
    :
fi

################################################################################
# QUOTA SUMMARY (optional, inv.sh)
################################################################################

emit_quota_summary_if_present() {
    local base_dir
    base_dir=$(dirname "$JSON_FILE")
    local quota_csv="$base_dir/quota_summary.csv"

    if [[ ! -f "$quota_csv" ]]; then
        return 0
    fi

    output_line ""
    output_line "═══════════════════════════════════════════════════════════════════════════════"
    output_line "QUOTA SUMMARY (from quota_summary.csv)"
    output_line "═══════════════════════════════════════════════════════════════════════════════"
    output_line ""

    if command -v python3 >/dev/null 2>&1; then
        local quota_out
        quota_out=$(python3 - "$quota_csv" "$SOURCE_REGION" "$TARGET_REGION" <<'PY'
import csv
import sys
from collections import defaultdict

quota_csv = sys.argv[1]
src_region = sys.argv[2]
tgt_region = sys.argv[3]

rows = []
with open(quota_csv, newline='', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    for r in reader:
        if not r:
            continue
        try:
            r['percentUsed'] = float(r.get('percentUsed', '') or 0)
        except ValueError:
            r['percentUsed'] = 0.0
        rows.append(r)

print(f"Quota metrics: {len(rows)}")

by_region = defaultdict(list)
for r in rows:
    by_region[r.get('region','Unknown')].append(r)

def emit_region(region: str):
    rs = by_region.get(region, [])
    if not rs:
        print(f"{region}: 0 metrics")
        return
    print(f"{region}: {len(rs)} metrics")
    top = sorted(rs, key=lambda x: x.get('percentUsed', 0.0), reverse=True)[:5]
    if top:
        print("Top 5 by percent used:")
        for t in top:
            rt = t.get('resourceType','')
            qm = t.get('quotaMetric','')
            lim = t.get('limit','')
            cur = t.get('currentUsage','')
            pu = t.get('percentUsed', 0.0)
            print(f"  - {rt} | {qm} | {cur}/{lim} ({pu:.0f}%)")

emit_region(src_region)
print("")
emit_region(tgt_region)
PY
        )

        while IFS= read -r line; do
            [[ -n "$line" ]] || continue
            output_line "$line"
        done <<< "$quota_out"
    else
        local total_lines
        total_lines=$(wc -l < "$quota_csv" 2>/dev/null || echo "0")
        output_line "Quota metrics: $((total_lines > 0 ? total_lines - 1 : 0))"
    fi
}

################################################################################
# SERVICE AVAILABILITY REPORT (inv.sh)
################################################################################

generate_service_availability_report() {
    output_line "╔════════════════════════════════════════════════════════════════════════════╗"
    output_line "║         Azure Inventory Comparative Analysis: Availability + Quota         ║"
    output_line "╚════════════════════════════════════════════════════════════════════════════╝"
    output_line ""
    output_line "Input: $JSON_FILE"
    output_line "Source Region: $SOURCE_REGION"
    output_line "Target Region: $TARGET_REGION"
    output_line "Generated: $(date)"
    output_line ""

    output_line "═══════════════════════════════════════════════════════════════════════════════"
    output_line "AVAILABILITY SUMMARY"
    output_line "═══════════════════════════════════════════════════════════════════════════════"
    output_line ""

    local summary
    summary=$(jq -r --arg src "$SOURCE_REGION" --arg tgt "$TARGET_REGION" '
        def avail($r): (.availability[]? | select(.region==$r) | .available) // false;
        {
            total: length,
            availableInBoth: ([.[] | select(avail($src) and avail($tgt))] | length),
            sourceOnly: ([.[] | select(avail($src) and (avail($tgt) | not))] | length),
            targetOnly: ([.[] | select((avail($src) | not) and avail($tgt))] | length),
            unavailableInBoth: ([.[] | select((avail($src) | not) and (avail($tgt) | not))] | length)
        }
    ' "$JSON_FILE" 2>/dev/null)

    if [[ -n "$summary" ]]; then
        output_line "Service Types Analyzed:          $(echo "$summary" | jq -r '.total')"
        output_line "Available in Both Regions:       $(echo "$summary" | jq -r '.availableInBoth')"
        output_line "Source Only (unavailable target):$(echo "$summary" | jq -r '.sourceOnly')"
        output_line "Target Only (unavailable source):$(echo "$summary" | jq -r '.targetOnly')"
        output_line "Unavailable in Both:             $(echo "$summary" | jq -r '.unavailableInBoth')"
    else
        output_line "Unable to summarize availability (unexpected JSON format)."
    fi

    output_line ""
    output_line "Top Unavailable in Target ($TARGET_REGION):"
    output_line "─────────────────────────────────────────────────────────────────────────────"
    jq -r --arg tgt "$TARGET_REGION" '
        def avail($r): (.availability[]? | select(.region==$r) | .available) // false;
        .[] | select(avail($tgt) | not) |
        "\(.serviceType) | inventoryCount=\(.inventoryCount // 0)"
    ' "$JSON_FILE" 2>/dev/null | head -15 | while IFS= read -r line; do
        [[ -n "$line" ]] || continue
        output_line "  - $line"
    done

    emit_quota_summary_if_present

    output_line ""
    output_line "═══════════════════════════════════════════════════════════════════════════════"
    output_line "Notes"
    output_line "═══════════════════════════════════════════════════════════════════════════════"
    output_line "- This report is based on inv.sh comparative availability output."
    output_line "- Quota summary is included when quota_summary.csv exists in the same folder."
}

# Function to write output (stdout or file)
output_line() {
    local line="$1"
    if [[ -n "$OUTPUT_FILE" ]]; then
        echo "$line" >> "$OUTPUT_FILE"
    else
        echo "$line"
    fi
}

# Initialize output file if specified
if [[ -n "$OUTPUT_FILE" ]]; then
    > "$OUTPUT_FILE"
fi

# If this is inv.sh's service availability JSON, generate that report and exit.
if [[ "$INPUT_SCHEMA" == "service_availability" ]]; then
    generate_service_availability_report
    if [[ -n "$OUTPUT_FILE" ]]; then
        echo ""
        echo "✓ Report generated: $OUTPUT_FILE"
    fi
    exit 0
fi

################################################################################
# HEADER
################################################################################

output_line "╔════════════════════════════════════════════════════════════════════════════╗"
if [[ "$INPUT_TYPE" == "inventory" ]]; then
    output_line "║      Azure Inventory Comparative Analysis: SKU & Provider Report          ║"
else
    output_line "║          Azure Service Comparative Analysis: SKU & Provider Report         ║"
fi
output_line "╚════════════════════════════════════════════════════════════════════════════╝"
output_line ""
if [[ "$INPUT_TYPE" == "inventory" ]]; then
    output_line "Analysis Type: Inventory-Based (Existing Resources)"
fi
output_line "Source Region: $SOURCE_REGION"
output_line "Target Region: $TARGET_REGION"
output_line "Generated: $(date)"
output_line ""

################################################################################
# SUMMARY STATISTICS
################################################################################

output_line "═══════════════════════════════════════════════════════════════════════════════"
output_line "SUMMARY STATISTICS"
output_line "═══════════════════════════════════════════════════════════════════════════════"
output_line ""

total_providers=$(jq '. | length' "$JSON_FILE")
full_match=$(jq '[.[] | select(.status == "FULL_MATCH")] | length' "$JSON_FILE")
src_extended=$(jq '[.[] | select(.status == "SOURCE_EXTENDED")] | length' "$JSON_FILE")
tgt_extended=$(jq '[.[] | select(.status == "TARGET_EXTENDED")] | length' "$JSON_FILE")
available_no_skus=$(jq '[.[] | select(.status == "AVAILABLE_NO_SKUS")] | length' "$JSON_FILE")
source_only=$(jq '[.[] | select(.status == "SOURCE_ONLY")] | length' "$JSON_FILE")
target_only=$(jq '[.[] | select(.status == "TARGET_ONLY")] | length' "$JSON_FILE")

output_line "Total Providers:               $total_providers"
output_line "  ✓ Full Match:                $full_match"
output_line "  ⟶ Source Extended (more):    $src_extended"
output_line "  ⟵ Target Extended (more):    $tgt_extended"
output_line "  ≈ Available (No SKUs):       $available_no_skus"
output_line "  ⊢ Source Only:               $source_only"
output_line "  ⊣ Target Only:               $target_only"
output_line ""

# Provider match percentage
available_in_both=$((total_providers - source_only - target_only))
if [[ $total_providers -gt 0 ]]; then
    match_pct=$((available_in_both * 100 / total_providers))
    output_line "Provider Availability Match: $available_in_both / $total_providers = ${match_pct}%"
    output_line ""
fi

    # Include quota summary for inventory-based runs when available
    if [[ "$INPUT_TYPE" == "inventory" ]]; then
        emit_quota_summary_if_present
    fi

################################################################################
# COMPUTE ANALYSIS
################################################################################

output_line "═══════════════════════════════════════════════════════════════════════════════"
output_line "MICROSOFT.COMPUTE - DETAILED SKU COMPARISON BY FAMILY/VERSION"
output_line "═══════════════════════════════════════════════════════════════════════════════"
output_line ""

compute_data=$(jq '.[] | select(.provider == "Microsoft.Compute")' "$JSON_FILE" 2>/dev/null)

if [[ -n "$compute_data" ]]; then
    src_count=$(echo "$compute_data" | jq '.sourceRegion.skuCount')
    tgt_count=$(echo "$compute_data" | jq '.targetRegion.skuCount')
    has_skus=$(echo "$compute_data" | jq '.sourceRegion.skus | length')
    
    output_line "SKU Counts:"
    output_line "  $SOURCE_REGION:    $src_count SKUs"
    output_line "  $TARGET_REGION: $tgt_count SKUs"
    output_line "  Difference:        $(($src_count - $tgt_count)) ($([[ $src_count -gt $tgt_count ]] && echo "Source has more" || echo "Target has more"))"
    output_line ""
    
    # Extract unique VM family versions only if data is available
    if [[ $has_skus -gt 0 ]]; then
        output_line "Family / Version Breakdown ($SOURCE_REGION | $TARGET_REGION | Diff):"
        output_line "─────────────────────────────────────────────────────────────────────────────"
        
        src_skus=$(echo "$compute_data" | jq -r '.sourceRegion.skus[].name' 2>/dev/null | sort -u)
        tgt_skus=$(echo "$compute_data" | jq -r '.targetRegion.skus[].name' 2>/dev/null | sort -u)
        
        # Extract families from source region
        if [[ -n "$src_skus" ]]; then
            echo "$src_skus" | sed 's/-Type.*//' | sort -u | while read family; do
                src_family_count=$(echo "$src_skus" | grep -c "^${family}-" 2>/dev/null || true)
                tgt_family_count=$(echo "$tgt_skus" | grep -c "^${family}-" 2>/dev/null || true)
                diff=$((src_family_count - tgt_family_count))
                
                # Format with padding
                printf "  %-35s %4d | %-4d | %+4d\n" "$family" "$src_family_count" "$tgt_family_count" "$diff" | while read line; do
                    output_line "$line"
                done
            done
        fi
    else
        output_line "Family / Version Breakdown:"
        output_line "  (SKU details omitted - full data available in JSON)"
        output_line "  Source region has $src_count VM SKUs vs target region's $tgt_count"
        output_line "  Key difference: $([[ $src_count -gt $tgt_count ]] && echo "Source region offers more SKUs" || echo "Target region offers more SKUs")"
    fi
    
    output_line ""
else
    output_line "Microsoft.Compute: Not available in both regions"
    output_line ""
fi

################################################################################
# STORAGE ANALYSIS
################################################################################

output_line "═══════════════════════════════════════════════════════════════════════════════"
output_line "MICROSOFT.STORAGE - ACCOUNT TYPE COMPARISON"
output_line "═══════════════════════════════════════════════════════════════════════════════"
output_line ""

storage_data=$(jq '.[] | select(.provider == "Microsoft.Storage")' "$JSON_FILE" 2>/dev/null)

if [[ -n "$storage_data" ]]; then
    src_count=$(echo "$storage_data" | jq '.sourceRegion.skuCount')
    tgt_count=$(echo "$storage_data" | jq '.targetRegion.skuCount')
    status=$(echo "$storage_data" | jq -r '.status')
    
    output_line "Status: $status"
    output_line "SKU Counts: $SOURCE_REGION=$src_count, $TARGET_REGION=$tgt_count"
    output_line ""
    output_line "Account Types ($SOURCE_REGION | $TARGET_REGION):"
    output_line "─────────────────────────────────────────────────────────────────────────────"
    
    src_skus=$(echo "$storage_data" | jq -r '.sourceRegion.skus[].kind' 2>/dev/null | sort -u)
    tgt_skus=$(echo "$storage_data" | jq -r '.targetRegion.skus[].kind' 2>/dev/null | sort -u)
    
    # Get all unique kinds
    all_kinds=$(echo -e "$src_skus\n$tgt_skus" | sort -u)
    
    if [[ -n "$all_kinds" ]]; then
        echo "$all_kinds" | while read kind; do
            [[ -z "$kind" ]] && continue
            src_kind_count=$(echo "$storage_data" | jq "[.sourceRegion.skus[] | select(.kind == \"$kind\")] | length")
            tgt_kind_count=$(echo "$storage_data" | jq "[.targetRegion.skus[] | select(.kind == \"$kind\")] | length")
            
            # Format with padding
            printf "  %-30s %4d | %-4d\n" "$kind" "$src_kind_count" "$tgt_kind_count" | while read line; do
                output_line "$line"
            done
        done
    fi
    
    output_line ""
else
    output_line "Microsoft.Storage: Not available in both regions"
    output_line ""
fi

################################################################################
# PROVIDERS WITH NOTABLE DIFFERENCES
################################################################################

output_line "═══════════════════════════════════════════════════════════════════════════════"
output_line "PROVIDERS WITH NOTABLE DIFFERENCES (Top 15)"
output_line "═══════════════════════════════════════════════════════════════════════════════"
output_line ""

output_line "Format: Provider | Source Count | Target Count | Difference | Status"
output_line "─────────────────────────────────────────────────────────────────────────────"

jq -r '.[] | select(.sourceRegion.skuCount > 0 or .targetRegion.skuCount > 0) | 
    "\(.provider)|\(.sourceRegion.skuCount)|\(.targetRegion.skuCount)|\(.sourceRegion.skuCount - .targetRegion.skuCount)|\(.status)"' "$JSON_FILE" | \
    sort -t'|' -k4 -rn | head -15 | \
    while IFS='|' read provider src tgt diff status; do
        printf "%-35s %5s | %5s | %+5s | %s\n" "$provider" "$src" "$tgt" "$diff" "$status" | while read line; do
            output_line "$line"
        done
    done

output_line ""

################################################################################
# FOOTER
################################################################################

output_line "═══════════════════════════════════════════════════════════════════════════════"
output_line "Full comparison data available in:"
output_line "  JSON: $JSON_FILE"
output_line "  CSV:  ${JSON_FILE/_providers.json/_providers.csv}"
output_line "═══════════════════════════════════════════════════════════════════════════════"

if [[ -n "$OUTPUT_FILE" ]]; then
    echo ""
    echo "✓ Report generated: $OUTPUT_FILE"
fi
